site_name: WEB-programming
nav:
  - Home: index.md
  - 1 lab:
      - Task 1: 111/1.md
      - Task 2: 111/2.md
      - Task 3: 111/3.md
      - Task 4: 111/4.md
      - Task 5: 111/5.md
theme:
  name: bootstrap4