site_name: 'Отчёт по проекту'
theme:
  name: 'material'
  palette:
    scheme: default
    primary: pink
    accent: pink

nav:
  - Главная: index.md
  - Сайт "Список научных конференций": Website.md
  - Django Administration: Django.md

extra_css:
  - css/extra.css
