# Generated by Django 5.1.3 on 2024-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="dt_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="lease",
            name="dt_start",
            field=models.DateField(),
        ),
    ]
